// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDd1Gv5HT2sM95vaaHgYzn-2T4A9YEx8E4',
    appId: '1:102088530906:web:d9491d1a5839c5cd113ee3',
    messagingSenderId: '102088530906',
    projectId: 'home-bites-ddcae',
    authDomain: 'home-bites-ddcae.firebaseapp.com',
    storageBucket: 'home-bites-ddcae.firebasestorage.app',
    measurementId: 'G-SS3V5H1N0G',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNssublgLJlPQnwK-qvJtU6iKo6m4LDmk',
    appId: '1:102088530906:ios:19c694c925cbafd7113ee3',
    messagingSenderId: '102088530906',
    projectId: 'home-bites-ddcae',
    storageBucket: 'home-bites-ddcae.firebasestorage.app',
    iosBundleId: 'com.example.homebitesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNssublgLJlPQnwK-qvJtU6iKo6m4LDmk',
    appId: '1:102088530906:ios:19c694c925cbafd7113ee3',
    messagingSenderId: '102088530906',
    projectId: 'home-bites-ddcae',
    storageBucket: 'home-bites-ddcae.firebasestorage.app',
    iosBundleId: 'com.example.homebitesApp',
  );
}
